config/routes.rb
Rails.application.routes.draw do
  root 'cocktails#index'
  mount Attachinary::Engine => "/attachinary"

  resources :cocktails, only: %i(index new show create) do
    resources :doses, only: %i(new create)
  end
  resources :doses, only: %i(destroy)


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
  has_attachment :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  # validates_uniqueness_of :dose_id, :scopes => [:cocktail_id, :ingredient_id]
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: %i(show)
  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    return render :new unless @cocktail.save
    redirect_to @cocktail
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: %i(new create)
  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    return render 'cocktails/show' unless @dose.save
    redirect_to @cocktail
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to dose_path
  end

private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<h1>Tous les cocktails</h1>

<%= link_to "Ajouter un cocktail", new_cocktail_path %>
<br>
<ul>
  <% @cocktails.each do |cocktail| %>
    <li>
      <%= cocktail.name %> |
      <%= link_to "Détails", cocktail_path(cocktail.id) %>
      <% if cocktail.photo? %>
        <%= cl_image_tag cocktail.photo.path, width: 50, height: 75, crop: :fill %>
      <% end %>
    </li>
  <% end %>
</ul>


<%#= cl_image_tag("cp9tkksldvflkkzyh6n1.jpg",
      width: 400, height: 300, crop: :fill) %>

app/views/cocktails/new.html.erb
<h1>Créer votre cocktail</h1>

<h3>
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name, hint: 'Check if it does not exist first' %>
    <%= f.input :photo, as: :attachinary %>
    <%= f.button :submit %>
  <% end %>
</h3>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<br>
<% if @cocktail.photo? %>
  <%= cl_image_tag @cocktail.photo.path, width: 200, height: 300, crop: :fill %>
<% end %>
<ul>
  <% @cocktail.doses.each do |dose| %>
    <li><%= dose.ingredient.name %> <%= dose.description %></li>
  <% end %>
</ul>

<%= render '/doses/form', dose: @dose, cocktail: @cocktail %>

<br>
<%= link_to "Retour à la liste", '/' %>


<%#= cl_image_tag("cp9tkksldvflkkzyh6n1.jpg",
      width: 400, height: 300, crop: :fill) %>

app/views/doses/_form.html.erb
<h3>Ajouter une dose dans votre cocktail</h3>

<p>
  <%= simple_form_for [cocktail, dose] do |f| %>
    <%= f.input :description, hint: 'en cl ou ml' %>
    <%= f.association :ingredient, collection: Ingredient.all %>
    <%= f.submit "Create Dose", class: "btn btn-info" %>
  <% end %>
</p>

app/views/doses/new.html.erb
<h1>Ajouter une dose dans votre cocktail</h1>

<h3>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description, hint: 'en cl' %>
    <%= f.association :ingredient, collection: Ingredient.all %>
    <%= f.button :submit %>
  <% end %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "http://res.cloudinary.com/difzyvscc/image/upload/c_crop,h_126,w_100,x_150,y_50/v1510325397/axyja4mfude0maneesue.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>